754 sso saml support
mcneilco/acas pull request #755
Opened 2021-05-26 00:23 UTC by brianbolt

2021-06-02 21:02 UTC, bffrost requested changes

2021-06-02 21:02 UTC, bffrost commented on modules/ServerAPI/src/server/routes/AuthorRoutes.coffee
> +diffSystemRolesWithSaved = (userName, systemRoles, savedSystemRoles, matchKeys, callback) ->
I see, matchKeys makes this more flexible

2021-06-03 20:18 UTC, brianbolt commented on modules/ServerAPI/src/server/CustomerSpecificServerFunctions.coffee
> +			password: 'saml managed password'
Agreed, I will set it to null as it doesn't makes sense to fill it in.   In either case, it wouldn't allow login as the password needs to be hashed for it to work.

2021-06-03 20:40 UTC, bffrost commented on modules/ServerAPI/src/server/routes/AuthorRoutes.coffee
> +				callback json, 500
Sorry why's this a 500 now? This looks like the successful response

2021-06-03 20:48 UTC, bffrost approved these changes
LGTM! Super excited to try this out.

2021-06-03 20:49 UTC, merged